### ISSUE TITLE
팔로우 날짜

### ISSUE THREAD

**Issue by shurielS2** [gunyu1019/chzzk_py#16]
혹시 팔로우 날짜 나오게 업데이트 하실 생각은 없으시나요?
파이선 배우는겸 이거루 챗봇만드는데.. 팔로우 날짜가 none값이라 너무 아쉽네요 ㅠㅠㅠ

**Comment by gunyu1019** [comment]
팔로우 날짜가 나오게 하는 업데이트가 무엇인지 자세한 설명을 부탁드려도 될까요?

**Comment by shurielS2** [comment]
안녕하세요 제가 코딩을 체계적으로 배운적이없어 설명내용이 틀릴 수 있어서 이해 안가시는 부분이있다면 좀 더 질문 주세요 
chzzkpy.chat.ChatMessage를 지정하고 profile 출력 속성에 following_date 값이 해당 유저의 팔로잉 날짜를 표기하는 건가 했는데 none 값만 리턴 되더라구요 이 부분이 원래 팔로잉 날짜를 표기하는 부분이 아닌가 해서 업뎃이 가능한가 해서 질문드렸습니다...
원문을 수정 해볼까했는데 이게 지식이 없다보니 이해하기가 넘 어렵네요 ㅎㅎㅎ
 message.profile.following_date 를  사용해서 팔로잉 날짜를 계산하려고 했습니다.

**Comment by gunyu1019** [comment]
저의 개인적인 사정으로 직접적인 도움을 드리지 못한 점 양해 부탁드립니다. 
1차로 확인해본 결과, chzzk 채팅 통신 중에는 팔로우 날짜 정보를 주지 않고 있습니다. :( 
채팅을 치는 사용자의 팔로우 날짜를 불러오는 방법을 알아낼 수 있다면, 반영해드리도록 하겠습니다.

시간이 된다면 기능 구현이 가능한지 자세히 들여봐보도록 하겠습니다.

**Comment by shurielS2** [comment]
아닙니다!!! 덕분에 해보고싶은거 해볼수있어서 넘 좋았어요!!! 네이버 치지직API가 자바는 많은데 파이선으로 가져오는게 없어서 만들어주신 코드로 엄청 이것저것 많이 해봤습니다 ㅎㅎㅎ 감사합니다

**Comment by gunyu1019** [comment]
오랫동안 기다리게 해서 죄송합니다. chzzk의 웹소켓 통신을 한하여 팔로우 날짜를 구하는 방법을 찾지 못하였습니다. 방법을 찾은 경우 re-open 하고 안내해 드리도록 하겠습니다. 불편을 드려 대단히 죄송합니다.

**Comment by gunyu1019** [comment]
오래 기다리셨습니다. 
#24 - `client.manage.followers()` 기능을 통해 팔로우 날짜 조회 기능이 추가될 예정입니다.
다만 아쉬운 점은 채널 소유주만 확인할 수 있다는 점입니다.
