### ISSUE TITLE
[BUG] 일부 스트리머들의 채팅창에서 client.send_chat가 동작되지 않음

### ISSUE THREAD

**Issue by poopki2018** [gunyu1019/chzzk_py#20]
일부 스트리머들의 채팅창에서 챗봇 (Chat-Bot)예제에서 client.send_chat을 사용하여 채팅을 보내도 채팅이 보이지 않는 증상이 발견되어 리포트합니다.

안되는 채널 ID : 2563ae3f4527aac5e59a67c02676bf38 ,8527d2b16d1b86e983a1f8edae36b537, 8c056c1ef23703ea3fbad1f93d4d14f7, 55970f7de3bf2ea088b415cc8d1a46f9
가능한 채널 ID : b83ec2e9078ad5777c7fc90e80222377, b61999886b91fb3fa362cf17fef0fd31

위와같이 6개채널 중 2개 채널은 send_chat을 통해 메세지가 전달되어 채팅창에 표시되지만 나머지 3개 채널은 send_chat이 호출되어도 메세지가 채팅창에 출력되지 않습니다.

모두 aiohttp의 http_websocket.py 내부의 _send_frame 함수까지 정상적으로 호출하고 패킷을 전송하나 알 수 없는 이유로 채팅이 표시되지 않습니다.

로그인을 위한 2개 쿠키 값을 직전에 발급받아도 동일한 증상을 보입니다.

**Comment by gunyu1019** [comment]
일부 채널에서 채팅이 불가능한 현상을 확인하였으며, 개인 일정으로 인해 시간이 다소 걸릴 것으로 보입니다. 불편을 드려 대단히 죄송합니다. 조속히 조치할 수 있도록 노력하겠습니다.

**Comment by poopki2018** [comment]
확인해주셔서 너무너무 감사드립니다!!

**Comment by gunyu1019** [comment]
저의 개인 일정 문제로 3주 이상의 늦은 처리 죄송합니다. 

chzzkpy의 웹소켓을 송.수신하는 값과 치지직 서비스의 웹소켓 통신 값을 대조해본 결과 문제가 없는 것으로 확인되었습니다. 
위 나열된 4개의 채널은 허락없이 `chzzkpy` 패키지를 직접 테스트를 하는 것은 방송인에게 해를 끼칠 수 있다고 판단하여 직접 테스트 하지는 못했습니다. 따라서 NAB(Not A Bug) 처리하도록 하겠습니다. 

만일 동일한 증상이 계속된다면, 아래의 내용을 코드에 추가하여 송.수신한 패킷 값을 알려주시면 진심으로 감사하겠습니다.
chzzkpy는 logging 모듈을 적극 활용합니다. 
DEBUG 레벨로 설정하면 치지직 서비스와 어떤 웹소켓 패킷을 주고받는지 확인해보실 수 있습니다.
```py
import logging 

command = logging.StreamHandler()
command.setFormatter(logging_format)
logging_format = logging.Formatter('[%(asctime)s | %(name)s | %(levelname)s]: %(message)s', "%Y-%m-%d %p %I:%M:%S"

_log = get_logger()
_log.addHandler(command)
```

**Comment by poopki2018** [comment]
[debug.txt](https://github.com/user-attachments/files/17688600/debug.txt)
안녕하세요, 확인 너무 감사드립니다.

말씀해주신대로 logging 모듈을 사용해 gateway와 chat_client에 디버거 로거를 동작시킨 결과 첨부드린 파일과 같이 나타났습니다.

정상적으로 채팅이 올라오는 채널의 경우 return값이  {'svcid': 'game', 'ver': '1', 'bdy': [{'svcid': 'game', 'cid': 'N1UcBh', 'mbrCnt': 17, 'uid': 'f5ab76bfc94b60a90329cabd2bfeee81', 'profile': '{"userIdHash":"f5ab76bfc94b60a90329cabd2bfeee81","nickname":"쿠키삼봇","profileImageUrl":"","userRoleCode":"common_user","badge":null,"title":null,"verifiedMark":false,"activityBadges":[],"streamingProperty":{"nicknameColor":{"colorCode":"CC000"},"activatedAchievementBadgeIds":[]}}', 'msg': '풉키ㅡ님, 안녕하세요!', 'msgTypeCode': 1, 'msgStatusType': 'NORMAL', 'extras': '{"chatType": "STREAMING", "emojis": "", "osType": "PC", "streamingChannelId": "N1UcBh"}', 'ctime': 1731168571097, 'utime': 1731168571097, 'msgTid': None, 'msgTime': 1731168571097}], 'cmd': 93101, 'tid': '3', 'cid': 'N1UcBh'}

인 반면 채팅이 올라오지 않는 채널의 경우 return 값이 아래와 같습니다.
{'svcid': 'game', 'ver': '1', 'bdy': {'messageTime': 1731168949625, 'blindType': 'BLIND', 'blindUserId': None, 'serviceId': 'game', 'message': None, 'userId': 'f5ab76bfc94b60a90329cabd2bfeee81', 'channelId': 'N1Ub57'}, 'cmd': 94008, 'tid': None, 'cid': 'N1Ub57'}
확인해주시면 감사드리겠습니다.

**Comment by poopki2018** [comment]
BLIND처리되는것으로 보아 봇을 매니저 설정을 해보겠습니다
